name: Deploy to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chenxianhua123/${{ variables.CONTAINER_NAME }}:latest

      - name: Push Docker Image to Docker Hub
        run: chenxianhua123/${{ variables.CONTAINER_NAME }}

      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: 47.120.3.222
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            docker pull ychenxianhua123/${{ variables.CONTAINER_NAME }}
            docker stop ${{ variables.CONTAINER_NAME }} || true
            docker rm ${{ variables.CONTAINER_NAME }} || true
            docker run -d --name ${{ variables.CONTAINER_NAME }} -p 5431:8080 your-docker-username/${{ variables.CONTAINER_NAME }}
